// Curated list of major world cities for the city autocomplete picker.
//
// Stored as plain city names (canonical casing, no country) so they stay
// compatible with existing `home_city` values and the `lower(trim(city))`
// matching used in discovery. De-duplicated and sorted alphabetically at the
// bottom of this file.
//
// This is intentionally a bundled list (no external API / key). Users in
// towns not on the list can still free-type their city; see normalizeCity.

const RAW_CITIES: string[] = [
  // Europe
  "Lisbon",
  "Porto",
  "Madrid",
  "Barcelona",
  "Valencia",
  "Seville",
  "London",
  "Manchester",
  "Birmingham",
  "Edinburgh",
  "Glasgow",
  "Dublin",
  "Paris",
  "Lyon",
  "Marseille",
  "Nice",
  "Bordeaux",
  "Toulouse",
  "Berlin",
  "Munich",
  "Hamburg",
  "Frankfurt",
  "Cologne",
  "Stuttgart",
  "Düsseldorf",
  "Rome",
  "Milan",
  "Naples",
  "Turin",
  "Florence",
  "Venice",
  "Bologna",
  "Amsterdam",
  "Rotterdam",
  "The Hague",
  "Utrecht",
  "Brussels",
  "Antwerp",
  "Ghent",
  "Vienna",
  "Zurich",
  "Geneva",
  "Basel",
  "Bern",
  "Lucerne",
  "Copenhagen",
  "Aarhus",
  "Stockholm",
  "Gothenburg",
  "Malmö",
  "Oslo",
  "Bergen",
  "Helsinki",
  "Reykjavik",
  "Warsaw",
  "Krakow",
  "Wroclaw",
  "Gdansk",
  "Prague",
  "Brno",
  "Budapest",
  "Bucharest",
  "Sofia",
  "Belgrade",
  "Zagreb",
  "Split",
  "Ljubljana",
  "Bratislava",
  "Athens",
  "Thessaloniki",
  "Istanbul",
  "Ankara",
  "Izmir",
  "Antalya",
  "Moscow",
  "Saint Petersburg",
  "Kyiv",
  "Kharkiv",
  "Minsk",
  "Vilnius",
  "Riga",
  "Tallinn",
  "Luxembourg",
  "Monaco",
  "Andorra la Vella",
  "Valletta",
  "Nicosia",
  "Tbilisi",
  "Yerevan",
  "Baku",

  // Middle East
  "Dubai",
  "Abu Dhabi",
  "Sharjah",
  "Doha",
  "Kuwait City",
  "Manama",
  "Muscat",
  "Riyadh",
  "Jeddah",
  "Mecca",
  "Amman",
  "Beirut",
  "Jerusalem",
  "Tel Aviv",
  "Baghdad",
  "Tehran",
  "Isfahan",
  "Damascus",

  // Africa
  "Cairo",
  "Alexandria",
  "Giza",
  "Casablanca",
  "Rabat",
  "Marrakesh",
  "Tangier",
  "Tunis",
  "Algiers",
  "Tripoli",
  "Lagos",
  "Abuja",
  "Accra",
  "Nairobi",
  "Mombasa",
  "Kampala",
  "Dar es Salaam",
  "Addis Ababa",
  "Kigali",
  "Dakar",
  "Abidjan",
  "Cape Town",
  "Johannesburg",
  "Pretoria",
  "Durban",
  "Luanda",
  "Maputo",
  "Harare",
  "Windhoek",
  "Gaborone",
  "Khartoum",

  // Asia
  "Tokyo",
  "Osaka",
  "Kyoto",
  "Yokohama",
  "Nagoya",
  "Sapporo",
  "Fukuoka",
  "Seoul",
  "Busan",
  "Incheon",
  "Beijing",
  "Shanghai",
  "Guangzhou",
  "Shenzhen",
  "Chengdu",
  "Chongqing",
  "Wuhan",
  "Xi'an",
  "Hangzhou",
  "Nanjing",
  "Hong Kong",
  "Macau",
  "Taipei",
  "Kaohsiung",
  "Singapore",
  "Bangkok",
  "Chiang Mai",
  "Phuket",
  "Pattaya",
  "Kuala Lumpur",
  "George Town",
  "Johor Bahru",
  "Jakarta",
  "Surabaya",
  "Bandung",
  "Denpasar (Bali)",
  "Ubud",
  "Manila",
  "Cebu City",
  "Quezon City",
  "Davao City",
  "Hanoi",
  "Ho Chi Minh City",
  "Da Nang",
  "Phnom Penh",
  "Siem Reap",
  "Vientiane",
  "Yangon",
  "Mumbai",
  "Thane",
  "Delhi",
  "New Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Goa",
  "Kochi",
  "Colombo",
  "Kathmandu",
  "Dhaka",
  "Karachi",
  "Lahore",
  "Islamabad",
  "Kabul",
  "Tashkent",
  "Almaty",
  "Astana",
  "Ulaanbaatar",

  // Oceania
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Adelaide",
  "Canberra",
  "Gold Coast",
  "Auckland",
  "Wellington",
  "Christchurch",
  "Queenstown",
  "Suva",
  "Nadi",
  "Honolulu",

  // North America
  "New York",
  "Los Angeles",
  "San Francisco",
  "San Diego",
  "San Jose",
  "Chicago",
  "Houston",
  "Dallas",
  "Austin",
  "San Antonio",
  "Phoenix",
  "Seattle",
  "Portland",
  "Denver",
  "Las Vegas",
  "Miami",
  "Orlando",
  "Tampa",
  "Atlanta",
  "Boston",
  "Philadelphia",
  "Washington",
  "Baltimore",
  "Nashville",
  "New Orleans",
  "Charlotte",
  "Detroit",
  "Minneapolis",
  "Salt Lake City",
  "Pittsburgh",
  "Kansas City",
  "St. Louis",
  "Toronto",
  "Vancouver",
  "Montreal",
  "Calgary",
  "Ottawa",
  "Edmonton",
  "Quebec City",
  "Winnipeg",
  "Halifax",
  "Mexico City",
  "Guadalajara",
  "Monterrey",
  "Cancún",
  "Playa del Carmen",
  "Tulum",
  "Puerto Vallarta",
  "Tijuana",
  "Oaxaca",
  "Mérida",
  "Havana",
  "Santo Domingo",
  "San Juan",
  "Kingston",
  "Panama City",
  "San José",
  "Guatemala City",
  "San Salvador",
  "Tegucigalpa",
  "Managua",

  // South America
  "São Paulo",
  "Rio de Janeiro",
  "Brasília",
  "Salvador",
  "Fortaleza",
  "Belo Horizonte",
  "Curitiba",
  "Florianópolis",
  "Recife",
  "Porto Alegre",
  "Buenos Aires",
  "Córdoba",
  "Rosario",
  "Mendoza",
  "Santiago",
  "Valparaíso",
  "Lima",
  "Cusco",
  "Arequipa",
  "Bogotá",
  "Medellín",
  "Cali",
  "Cartagena",
  "Quito",
  "Guayaquil",
  "Caracas",
  "Montevideo",
  "Asunción",
  "La Paz",
  "Santa Cruz de la Sierra",
];

export const CITIES: string[] = Array.from(new Set(RAW_CITIES)).sort((a, b) =>
  a.localeCompare(b)
);

// Small connector words kept lowercase when they appear in the middle of a name.
const CONNECTORS = new Set(["and", "of", "the", "de", "del", "da", "la", "el"]);

/**
 * Normalize a free-typed city string so casing/whitespace are clean:
 * - trims outer whitespace
 * - collapses internal runs of whitespace to a single space
 * - title-cases each word (first letter upper, rest lower)
 * - keeps small connector words lowercase when not the first word
 * Returns "" for empty/whitespace-only input.
 */
export function normalizeCity(input: string): string {
  const trimmed = input.trim().replace(/\s+/g, " ");
  if (!trimmed) return "";
  return trimmed
    .split(" ")
    .map((word, index) => {
      const lower = word.toLowerCase();
      if (index > 0 && CONNECTORS.has(lower)) return lower;
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join(" ");
}
