import { Archetype, VibeDimension } from "./types";

export const ARCHETYPES: Record<VibeDimension, Archetype> = {
  culture: {
    key: "culture",
    name: "The Cultural Nomad",
    emoji: "🏛️",
    gradientFrom: "#1A6899",
    gradientTo: "#2C7CB2",
    description: "You go deep, not wide. You're in the museum before it opens and the local spot after it closes.",
    insight: "You don't just visit places — you actually learn them. Pair you with someone who matches that pace, not someone who wants to rush you through.",
    compatibleWith: ["food", "night"],
  },
  social: {
    key: "social",
    name: "The Social Butterfly",
    emoji: "🦋",
    gradientFrom: "#FF6B4A",
    gradientTo: "#E0512C",
    description: "You came for one thing and stayed for the people. You know everyone's name by day two.",
    insight: "A room of strangers doesn't scare you — it's basically an invitation. We'll keep your feed full of people and plans, not just places.",
    compatibleWith: ["night", "adventure"],
  },
  night: {
    key: "night",
    name: "The Night Owl Explorer",
    emoji: "🌙",
    gradientFrom: "#0A2545",
    gradientTo: "#1A6899",
    description: "Things reveal themselves after dark and you know it. Mornings are for recovery.",
    insight: "We'll weight your matches toward people who don't expect a reply before noon.",
    compatibleWith: ["social", "food"],
  },
  food: {
    key: "food",
    name: "The Food Pilgrim",
    emoji: "🍜",
    gradientFrom: "#B5621E",
    gradientTo: "#D98C5F",
    description: "You plan your days around meals, and you'll take the long way for the right place.",
    insight: "Your matches will skew toward people who treat a good meal as the whole point of the day, not a pit stop.",
    compatibleWith: ["culture", "night"],
  },
  adventure: {
    key: "adventure",
    name: "The Free Spirit",
    emoji: "🌊",
    gradientFrom: "#1A8C6A",
    gradientTo: "#1FB58A",
    description: "No plan is the plan. You decide late, travel light, and somehow always find the right people.",
    insight: "Rigid itineraries make you twitchy. We'll surface the loose, see-where-it-goes plans first.",
    compatibleWith: ["social", "wellness"],
  },
  wellness: {
    key: "wellness",
    name: "The Wellness Wanderer",
    emoji: "🧘",
    gradientFrom: "#3D6E55",
    gradientTo: "#5A9E78",
    description: "Slow, intentional, unbothered. You need at least one afternoon with absolutely nothing planned.",
    insight: "You recharge in quiet, not chaos. We'll lean your matches toward people who won't fill every hour.",
    compatibleWith: ["culture", "adventure"],
  },
};
